### ISSUE TITLE
No longer building on nightly

### ISSUE THREAD

**Issue by PudgePacket** [DaGenix/rust-crypto#206]
rust-crypto fails to build on nightly rustc 0.13.0-nightly (ad9e75938 2015-01-05 00:26:28 +0000).

src/http/common.rs:8:16: 8:24 error: unresolved import `std::num::Unsigned`. There is no `Unsigned` in `std::num`
src/http/common.rs:8 use std::num::{Unsigned, NumCast, Int, cast};
